### ISSUE TITLE
安装成后 进入页面 点击 一键自动化 One-Click 里得 Submit 就出现如下得错误，请问下怎么解决

### ISSUE THREAD

**Issue by anstonjie** [Kedreamix/Linly-Dubbing#3]
[BiliBili] Format(s) 4K 超清, 1080P 高码率, 1080P 高清, 720P 高清 are missing; you have to login or become a premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[BiliBili] 1406337061: Extracting chapters
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\linly_dubbing\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\ProgramData\anaconda3\envs\linly_dubbing\lib\site-packages\gradio\route_utils.py", line 288, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\anaconda3\envs\linly_dubbing\lib\site-packages\gradio\blocks.py", line 1931, in process_api
    result = await self.call_function(
  File "C:\ProgramData\anaconda3\envs\linly_dubbing\lib\site-packages\gradio\blocks.py", line 1516, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\ProgramData\anaconda3\envs\linly_dubbing\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\ProgramData\anaconda3\envs\linly_dubbing\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\anaconda3\envs\linly_dubbing\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\ProgramData\anaconda3\envs\linly_dubbing\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "E:\ai3\Linly-Dubbing\tools\do_everything.py", line 133, in do_everything
    success, output_video = process_video(info, root_folder, resolution,
  File "E:\ai3\Linly-Dubbing\tools\do_everything.py", line 29, in process_video
    if info.endswith('.mp4'):
AttributeError: 'dict' object has no attribute 'endswith'

**Comment by Kedreamix** [comment]
你好，感谢你的关注，你这个是输入的是视频的文件路径还是视频url

**Comment by anstonjie** [comment]
是视频URL,我看后台返回得是json格式得数据

**Comment by Kedreamix** [comment]
是我的一个bug，我会尽快今天内修改代码，可能是一个格式判断问题

**Comment by Kedreamix** [comment]
29行修改成即可
        if isinstance(info, str) and info.endswith('.mp4'):

**Comment by anstonjie** [comment]
好的，我试试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月18日 20:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kedreamix/Linly-Dubbing] 安装成后 进入页面 点击 一键自动化 One-Click 里得 Submit 就出现如下得错误，请问下怎么解决 (Issue #3) |

29行修改成即可
if isinstance(info, str) and info.endswith('.mp4'):

**Comment by Kedreamix** [comment]
我已经更新最新代码，可以尝试一下，如果有问题可以进行沟通交流

**Comment by anstonjie** [comment]
好的马上更新测试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月19日 08:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kedreamix/Linly-Dubbing] 安装成后 进入页面 点击 一键自动化 One-Click 里得 Submit 就出现如下得错误，请问下怎么解决 (Issue #3) |

我已经更新最新代码，可以尝试一下，如果有问题可以进行沟通交流

**Comment by anstonjie** [comment]
又出问题了

2024-08-19 12:46:06.404 | INFO     | tools.step000_video_downloader:download_single_video:35 - Video already downloaded in videos\村长台钓加拿大\20240805 英文无字幕 阿里这小子在水城威尼斯发来问候
2024-08-19 12:46:06.405 | INFO     | tools.do_everything:process_video:43 - Process video in videos\村长台钓加拿大\20240805 英文无字幕 阿里这小子在水城威尼斯发来问候
2024-08-19 12:46:06.406 | INFO     | tools.step010_demucs_vr:separate_all_audio_under_folder:114 - Audio already separated in videos\村长台钓加拿大\20240805 英文无字幕 阿里这小子在水城威尼斯发来问候
2024-08-19 12:46:06.406 | INFO     | tools.step010_demucs_vr:separate_all_audio_under_folder:115 - All audio separated under videos\村长台钓加拿大\20240805 英文无字幕 阿里这小子在水城威尼斯发来问候
2024-08-19 12:46:06.407 | INFO     | tools.step020_asr:transcribe_audio:70 - Transcribing videos\村长台钓加拿大\20240805 英文无字幕 阿里这小子在水城威尼斯发来问候\audio_vocals.wav
Warning: audio is shorter than 30s, language detection may be inaccurate.
Detected language: en (0.82) in first 30s of audio...
2024-08-19 12:46:28.011 | ERROR    | tools.step021_asr_whisperx:load_diarize_model:66 - Failed to load diarization model in 20.03s due to An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
2024-08-19 12:46:28.018 | INFO     | tools.step021_asr_whisperx:load_diarize_model:67 - You have not set the HF_TOKEN, so the pyannote/speaker-diarization-3.1 model could not be downloaded.
2024-08-19 12:46:28.019 | INFO     | tools.step021_asr_whisperx:load_diarize_model:68 - If you need to use the speaker diarization feature, please request access to the pyannote/speaker-diarization-3.1 model. Alternatively, you can choose not to enable this feature.
2024-08-19 12:46:28.019 | ERROR    | tools.do_everything:process_video:60 - Error processing video (英文无字幕) 阿里这小子在水城威尼斯发来问候: 'NoneType' object is not callable

**Comment by Kedreamix** [comment]
如果开启人声分离的模式的话，需要设置.env里面的HF_TOKEN，要不然可以关闭人声分离模式

**Comment by Kedreamix** [comment]
已经重新更新代码，已解决bug
