### ISSUE TITLE
ModuleNotFoundError: No module named 'TTS.api'

### ISSUE THREAD

**Issue by shockgun92** [Kedreamix/Linly-Dubbing#37]
I successfully installed everything, but when I run the webUI, an error occurs saying the 'TTS' module cannot be found. Could someone provide me with some solutions? I am using a locally downloaded TTS model; do I need to make any modifications in the environment file?

```
(linly_dubbing) D:\Linly-Dubbing>python webui.py
C:\Users\thai\anaconda3\envs\linly_dubbing\lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
C:\Users\thai\anaconda3\envs\linly_dubbing\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:43: UserWarning: torchaudio._backend.get_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  backend = torchaudio.get_audio_backend()
INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [allow_tf32, disable_jit_profiling]
INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
C:\Users\thai\anaconda3\envs\linly_dubbing\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:45: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  from speechbrain.pretrained import (
C:\Users\thai\anaconda3\envs\linly_dubbing\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:53: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend(backend)
C:\Users\thai\anaconda3\envs\linly_dubbing\lib\site-packages\pyannote\audio\tasks\segmentation\mixins.py:37: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData
INFO:root:New registry table added: preprocessor_classes
Key Conformer already exists in model_classes, re-register
INFO:root:New registry table added: adaptor_classes
Key Linear already exists in adaptor_classes, re-register
Key TransformerDecoder already exists in decoder_classes, re-register
Key LightweightConvolutionTransformerDecoder already exists in decoder_classes, re-register
Key LightweightConvolution2DTransformerDecoder already exists in decoder_classes, re-register
Key DynamicConvolutionTransformerDecoder already exists in decoder_classes, re-register
Key DynamicConvolution2DTransformerDecoder already exists in decoder_classes, re-register
INFO:root:New registry table added: lid_predictor_classes
Traceback (most recent call last):
  File "D:\Linly-Dubbing\webui.py", line 6, in <module>
    from tools.step040_tts import generate_all_wavs_under_folder
  File "D:\Linly-Dubbing\tools\step040_tts.py", line 11, in <module>
    from .step042_tts_xtts import tts as xtts_tts
  File "D:\Linly-Dubbing\tools\step042_tts_xtts.py", line 2, in <module>
    from TTS.api import TTS
ModuleNotFoundError: No module named 'TTS.api'


```

**Comment by bytrix** [comment]
还是报这个错误
