### ISSUE TITLE
依赖解析出问题

### ISSUE THREAD

**Issue by qunyinghuicui-copy** [Kedreamix/Linly-Dubbing#39]
ERROR: Exception:
Traceback (most recent call last):
  File "D:\anaconda\envs\linly_dubbing\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "D:\anaconda\envs\linly_dubbing\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "D:\anaconda\envs\linly_dubbing\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "D:\anaconda\envs\linly_dubbing\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "D:\anaconda\envs\linly_dubbing\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "D:\anaconda\envs\linly_dubbing\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\anaconda\envs\linly_dubbing\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000

**Comment by joytsay** [comment]
@qunyinghuicui-copy  
https://github.com/Kedreamix/Linly-Dubbing/issues/32#issuecomment-2428815360
