### ISSUE TITLE
安裝上的問題

### ISSUE THREAD

**Issue by fatdennis** [Kedreamix/Linly-Dubbing#4]
我跟著步驟...一步一步搞，去到bash scripts/download.sh 就中止了.... 

(linly_dubbing) D:\Linly-Dubbing>bash scripts/download.sh
Windows 子系統 Linux 版沒有已安裝的發佈。

使用 'wsl.exe --list --online' 列出可用的發佈
和 'wsl.exe --install <Distro>' 來安裝。

您也可以造訪 Microsoft Store 來安裝發佈:
https://aka.ms/wslstore
Error code: Bash/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

(linly_dubbing) D:\Linly-Dubbing>bash scripts/download.sh
Windows 子系統 Linux 版沒有已安裝的發佈。

使用 'wsl.exe --list --online' 列出可用的發佈
和 'wsl.exe --install <Distro>' 來安裝。

您也可以造訪 Microsoft Store 來安裝發佈:
https://aka.ms/wslstore
Error code: Bash/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

(linly_dubbing) D:\Linly-Dubbing>

我用win11, anaconda... 有什麼辦法可以更進一步？

**Comment by Kedreamix** [comment]
你好，非常感谢你的关注，有几种方法可以解决这个问题：

1. 如果你已经安装了 Git，可以直接使用 Git Bash 终端来运行命令。

2. 如果没有 Git 终端，可以尝试以下操作：
   ```bash
   python scripts/modelscope_download.py
   ```

3. 手动下载模型文件并将其放置到相应文件夹下：
   ```bash
   wget -nc https://download.pytorch.org/torchaudio/models/wav2vec2_fairseq_base_ls960_asr_ls960.pth \
       -O models/ASR/whisper/wav2vec2_fairseq_base_ls960_asr_ls960.pth
   ```

把下载好的文件放到 `models/ASR/whisper` 文件夹中即可。

**Comment by fatdennis** [comment]
1) 有用GIT, 但還是沒認到  git bash; 
2) 用第二個指令，好像有些檔案下載了，有些還是下載不到...
3) 系統好像不認識這個指定。

(linly_dubbing) D:\Linly-Dubbing>python scripts/modelscope_download.py
2024-08-19 10:30:29,891 - modelscope - ERROR - The request model: qwen/Qwen1.5-1.B-Chat does not exist!
Traceback (most recent call last):
  File "D:\Linly-Dubbing\scripts\modelscope_download.py", line 14, in <module>
    snapshot_download('qwen/Qwen1.5-1.B-Chat', local_dir='models/LLM/Qwen1.5-1.8B-Chat')
  File "C:\Users\Dennis\pinokio\bin\miniconda\envs\linly_dubbing\lib\site-packages\modelscope\hub\snapshot_download.py", line 84, in snapshot_download
    return _snapshot_download(
  File "C:\Users\Dennis\pinokio\bin\miniconda\envs\linly_dubbing\lib\site-packages\modelscope\hub\snapshot_download.py", line 220, in _snapshot_download
    revision_detail = _api.get_valid_revision_detail(
  File "C:\Users\Dennis\pinokio\bin\miniconda\envs\linly_dubbing\lib\site-packages\modelscope\hub\api.py", line 499, in get_valid_revision_detail
    all_branches_detail, all_tags_detail = self.get_model_branches_and_tags_details(
  File "C:\Users\Dennis\pinokio\bin\miniconda\envs\linly_dubbing\lib\site-packages\modelscope\hub\api.py", line 584, in get_model_branches_and_tags_details
    handle_http_response(r, logger, cookies, model_id)
  File "C:\Users\Dennis\pinokio\bin\miniconda\envs\linly_dubbing\lib\site-packages\modelscope\hub\errors.py", line 118, in handle_http_response
    raise HTTPError(http_error_msg, response=response)
requests.exceptions.HTTPError: The request model: qwen/Qwen1.5-1.B-Chat does not exist!

(linly_dubbing) D:\Linly-Dubbing>wget -nc https://download.pytorch.org/torchaudio/models/wav2vec2_fairseq_base_ls960_asr_ls960.pth \
'wget' 不是內部或外部命令、可執行的程式或批次檔。

(linly_dubbing) D:\Linly-Dubbing>    -O models/ASR/whisper/wav2vec2_fairseq_base_ls960_asr_ls960.pth
'-O' 不是內部或外部命令、可執行的程式或批次檔。

**Comment by fatdennis** [comment]
第二步可以了！因為有一個typing mistake, 在modelscope_download.py 檔案內，用notepad修正一下，就可以繼續下載

https://github.com/Kedreamix/Linly-Dubbing/issues/4#issuecomment-2295557513

**Comment by Kedreamix** [comment]
好的没问题，我也已经更新了model_download.py文件
