### ISSUE TITLE
ModuleNotFoundError: No module named 'demucs.api'

### ISSUE THREAD

**Issue by lsjie1525** [Kedreamix/Linly-Dubbing#40]
Traceback (most recent call last):
  File "E:\software\Linly-Dubbing-main\webui.py", line 3, in <module>
    from tools.step010_demucs_vr import separate_all_audio_under_folder
  File "E:\software\Linly-Dubbing-main\tools\step010_demucs_vr.py", line 2, in <module>
    from demucs.api import Separator
ModuleNotFoundError: No module named 'demucs.api'

**Comment by Kedreamix** [comment]
这个应该是有关于demus的依赖没有安装，可以再看看介绍和主项目
Demucs

Demucs is an advanced sound separation model developed by the Facebook research team, designed to separate different sound sources from mixed audio. Although its architecture is simple, Demucs is powerful enough to isolate instruments, voices, and background noise, making it easier for users to perform post-processing and editing. Its user-friendly design has made it a preferred tool for many audio processing applications, including music production and post-production in films. More information can be found on the [Demucs project page](https://github.com/facebookresearch/demucs).
