### ISSUE TITLE
egde_tts

### ISSUE THREAD

**Issue by tangcan1600** [Kedreamix/Linly-Dubbing#9]
Traceback (most recent call last):
  File "E:\AI\Linly-Dubbing\Linly-Dubbing\tools\do_everything.py", line 55, in process_video
    generate_all_wavs_under_folder(folder, method = tts_method, target_language=tts_target_language, voice=voice)
  File "E:\AI\Linly-Dubbing\Linly-Dubbing\tools\step040_tts.py", line 153, in generate_all_wavs_under_folder
    wav_combined, wav_ori = generate_wavs(method, root, target_language, voice)
  File "E:\AI\Linly-Dubbing\Linly-Dubbing\tools\step040_tts.py", line 120, in generate_wavs
    wav, length = adjust_audio_length(output_path, end-start)
  File "E:\AI\Linly-Dubbing\Linly-Dubbing\tools\step040_tts.py", line 58, in adjust_audio_length
    stretch_audio(wav_path, target_path, ratio=speed_factor, sample_rate=sample_rate)
  File "D:\Users\tangtang1600\Anaconda3\envs\linly_dubbing\lib\site-packages\audiostretchy\stretch.py", line 355, in stretch_audio
    audio_stretch.open(input_path)
  File "D:\Users\tangtang1600\Anaconda3\envs\linly_dubbing\lib\site-packages\audiostretchy\stretch.py", line 61, in open
    self.open_wav(audio_file)
  File "D:\Users\tangtang1600\Anaconda3\envs\linly_dubbing\lib\site-packages\audiostretchy\stretch.py", line 98, in open_wav
    wav_file = Wave_read(audio_file)
  File "D:\Users\tangtang1600\Anaconda3\envs\linly_dubbing\lib\wave.py", line 163, in __init__
    self.initfp(f)
  File "D:\Users\tangtang1600\Anaconda3\envs\linly_dubbing\lib\wave.py", line 130, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id
edge tts在线生成的是压缩后的MP3，不是原始对的wav，librosa会提示检测不到wave的标志头

**Comment by Kedreamix** [comment]
好的，我处理一下这个bug，感谢提醒

**Comment by tangcan1600** [comment]
> 好的，我处理一下这个bug，感谢提醒，我排查了一下，因为是没有安装对应的库，可以pip install edge-tts即可

WhisperX好像在cpu模式下无法加载模型，会显示张量不匹配，WhisperX官网上说cpu模式下compute_type要设置成int8，你可以测试下

**Comment by tangcan1600** [comment]
> 好的，我处理一下这个bug，感谢提醒，我排查了一下，因为是没有安装对应的库，可以pip install edge-tts即可

WhisperX好像在cpu模式下无法加载模型，会显示张量不匹配，WhisperX官网上说cpu模式下compute_type要设置成int8，你可以测试下

**Comment by Kedreamix** [comment]
好滴，没有问题，这个问题我也遇到过了，我也来处理一下，mp3的问题已解决，很快会push代码上去
